#!/usr/bin/env bash
# deploy-db-production.sh
# Applies the complete database schema to a PRODUCTION Supabase project.
# Requires: DATABASE_URL env var pointing to the target PostgreSQL database.
# Usage: bash scripts/deploy-db-production.sh
#
# ─────────────────────────────────────────────────────────────────────────────
# Two-class migration architecture
# ─────────────────────────────────────────────────────────────────────────────
# This project maintains two classes of SQL migration files in
# packages/db/migrations/:
#
#   1. DRIZZLE-TRACKED migrations (in meta/_journal.json):
#      0000_naive_mentallo, 0001_curved_zaran, 0002_natural_exiles,
#      0003_worthless_quicksilver, 0004_tense_chronomancer,
#      0007_esg_dashboard_indexes
#      These are generated by `drizzle-kit generate` and applied by
#      `pnpm --filter @repo/db db:migrate` in journal order.
#
#   2. MANUAL SUPPLEMENT migrations (NOT in journal):
#      0001_rls_and_triggers.sql, 0003_phase4_pickup_transport.sql,
#      0004_intake_trigger_rls.sql, 0005_phase6_processing_dispatch_audit.sql,
#      0006_financial_records.sql, 0008_notifications_manuals.sql,
#      0009_historical_import.sql
#      These were not generated by drizzle-kit. They add FORCE RLS,
#      GRANTs, trigger functions, and supplemental tables that Drizzle's
#      schema definition layer cannot express (e.g., SECURITY DEFINER
#      triggers, per-tenant sequence creation). They must be applied
#      with psql AFTER the Drizzle journal migrations complete.
#
#      All manual files use IF NOT EXISTS / CREATE OR REPLACE / ADD COLUMN
#      IF NOT EXISTS guards so they are safe to apply after db:migrate
#      regardless of whether individual Drizzle steps touched those tables.
#
#   Apply order: db:migrate first (all journal entries at once), then
#   manual supplements in the order below (dependency order).
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIGRATIONS_DIR="$SCRIPT_DIR/../packages/db/migrations"

if [ -z "${DATABASE_URL:-}" ]; then
  echo "ERROR: DATABASE_URL is not set." >&2
  echo "Export it before running: export DATABASE_URL=postgresql://user:pass@host:5432/dbname" >&2
  exit 1
fi

echo "WARNING: This will apply ALL migrations to the database at:"
echo "  $DATABASE_URL"
echo ""
read -p "Continue? (y/N) " confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

echo "==> Step 1: Running Drizzle journal migrations (pnpm db:migrate)..."
pnpm --filter @repo/db db:migrate

echo "==> Step 2: Applying manual supplement SQL files in dependency order..."

apply() {
  local file="$MIGRATIONS_DIR/$1"
  echo "    Applying: $1"
  psql "$DATABASE_URL" -f "$file"
}

apply "0001_rls_and_triggers.sql"
apply "0003_phase4_pickup_transport.sql"
apply "0004_intake_trigger_rls.sql"
apply "0005_phase6_processing_dispatch_audit.sql"
apply "0006_financial_records.sql"
# 0007_esg_dashboard_indexes.sql is already applied by db:migrate (journal idx 5) — skip
apply "0008_notifications_manuals.sql"
apply "0009_historical_import.sql"

echo "==> Step 3: Verifying audit triggers..."
TRIGGER_COUNT=$(psql "$DATABASE_URL" -t -A -c "SELECT count(*) FROM information_schema.triggers WHERE trigger_name IN ('audit_intake_records','audit_processing_reports','audit_outbound_dispatches')")
if [ "$TRIGGER_COUNT" -eq 3 ]; then
  echo "    OK: All 3 audit triggers present."
else
  echo "    WARNING: Expected 3 audit triggers, found $TRIGGER_COUNT." >&2
  echo "    Run the following to diagnose:" >&2
  echo "    psql \$DATABASE_URL -c \"SELECT trigger_name FROM information_schema.triggers WHERE trigger_name LIKE 'audit_%'\"" >&2
  exit 1
fi

echo ""
echo "Production database deployment complete."
echo "Tables, triggers, RLS policies, GRANTs, and indexes are all applied."
echo "Audit triggers verified: intake_records, processing_reports, outbound_dispatches."
