#!/usr/bin/env bash
# setup-local-db.sh
# Builds the complete database schema from scratch on a fresh PostgreSQL instance.
# Requires: DATABASE_URL env var pointing to an empty PostgreSQL database.
# Usage: bash scripts/setup-local-db.sh
#
# ─────────────────────────────────────────────────────────────────────────────
# Two-class migration architecture
# ─────────────────────────────────────────────────────────────────────────────
# This project maintains two classes of SQL migration files in
# packages/db/migrations/:
#
#   1. DRIZZLE-TRACKED migrations (in meta/_journal.json):
#      0000_naive_mentallo, 0001_curved_zaran, 0002_natural_exiles,
#      0003_worthless_quicksilver, 0004_tense_chronomancer,
#      0007_esg_dashboard_indexes
#      These are generated by `drizzle-kit generate` and applied by
#      `pnpm --filter @repo/db db:migrate` in journal order.
#
#   2. MANUAL SUPPLEMENT migrations (NOT in journal):
#      0001_rls_and_triggers.sql, 0003_phase4_pickup_transport.sql,
#      0004_intake_trigger_rls.sql, 0005_phase6_processing_dispatch_audit.sql,
#      0006_financial_records.sql, 0008_notifications_manuals.sql,
#      0009_historical_import.sql
#      These were not generated by drizzle-kit. They add FORCE RLS,
#      GRANTs, trigger functions, and supplemental tables that Drizzle's
#      schema definition layer cannot express (e.g., SECURITY DEFINER
#      triggers, per-tenant sequence creation). They must be applied
#      with psql AFTER the Drizzle journal migrations complete.
#
#      All manual files use IF NOT EXISTS / CREATE OR REPLACE / ADD COLUMN
#      IF NOT EXISTS guards so they are safe to apply after db:migrate
#      regardless of whether individual Drizzle steps touched those tables.
#
#   Apply order: db:migrate first (all journal entries at once), then
#   manual supplements in the order below (dependency order).
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIGRATIONS_DIR="$SCRIPT_DIR/../packages/db/migrations"

if [ -z "${DATABASE_URL:-}" ]; then
  echo "ERROR: DATABASE_URL is not set." >&2
  echo "Export it before running: export DATABASE_URL=postgresql://user:pass@host:5432/dbname" >&2
  exit 1
fi

echo "==> Step 1: Running Drizzle journal migrations (pnpm db:migrate)..."
pnpm --filter @repo/db db:migrate

echo "==> Step 2: Applying manual supplement SQL files in dependency order..."

apply() {
  local file="$MIGRATIONS_DIR/$1"
  echo "    Applying: $1"
  psql "$DATABASE_URL" -f "$file"
}

apply "0001_rls_and_triggers.sql"
apply "0003_phase4_pickup_transport.sql"
apply "0004_intake_trigger_rls.sql"
apply "0005_phase6_processing_dispatch_audit.sql"
apply "0006_financial_records.sql"
# 0007_esg_dashboard_indexes.sql is already applied by db:migrate (journal idx 5) — skip
apply "0008_notifications_manuals.sql"
apply "0009_historical_import.sql"

echo "==> Step 3: Running Wolt seed data..."
pnpm --filter @repo/db seed:wolt

echo ""
echo "Database setup complete."
echo "Tables, triggers, RLS policies, GRANTs, and indexes are all applied."
echo "Wolt seed data is present."
